version: '3.9'

services:
  bsale-api:
    container_name: bsale_api
    image: bsale/api:v${VERSION}
    restart: unless-stopped
    env_file:
      - ${PWD}/.env
    ports:
      - '3000:3000'
    networks:
      - default

networks:
  default:
    name: bsale-net